### ISSUE TITLE
getOneCount 函数算法好像太简单了

### ISSUE THREAD

**Issue by assmdx** [fuxingZhang/row_count#1]

**Comment by fuxingZhang** [comment]
存在什么问题吗，有好的写法吗，希望学习一下

**Comment by fuxingZhang** [comment]
@assmdx 
存在什么问题吗，有好的写法吗，希望学习一下

**Comment by assmdx** [comment]
代码文件里面可能只有一部门是开发人员写的。其他的可能是项目文件或者生成器生成的一些

**Comment by fuxingZhang** [comment]
> 代码文件里面可能只有一部门是开发人员写的。其他的可能是项目文件或者生成器生成的一些

确实，没有考虑那么多，比较粗糙，仅仅是个小玩具，所以没有花费太多精力
